### ISSUE TITLE
Questions about codes.

### ISSUE THREAD

**Issue by vva1024** [Kevinz-code/SeVa#3]
Thank you for your excellent work! 

I have a few questions regarding the following lines of code:
https://github.com/Kevinz-code/SeVa/blob/d9284ff83b25b435d7d739da2261958bbdc18325/seva/train_dpo_ours.py#L213
https://github.com/Kevinz-code/SeVa/blob/d9284ff83b25b435d7d739da2261958bbdc18325/seva/train_dpo_ours.py#L218

Could you explain the purpose of multiplying by 2 in these lines? Is it to ensure that the training data is processed twice?

**Comment by Kevinz-code** [comment]
Hi, thanks for your attention.

This operation is similar to enlarge the training iterations by 2x. 

As verified by our experiments, 1x and 2x training data both improve the baseline results, but 2x data leads to more saturated and stable training, and a slightly higher performance, and is finally set as our default setting in our codebase.

Best,
Authors.

**Comment by Ivesfu** [comment]
Thanks for your quick reply! The issue is now resolved.
